name: Build Docker Image CI (1.8.0_py3.9.10_cuda11.1_ubuntu20.04)

env:
  UBUNTU_VERSION: "20.04"
  CUDA_VERSION: "11.1"
  CUDNN_VERSION: "8"

  PYTHON_VERSION: "3.9.10"

  PYTORCH_VERSION: "1.8.0"
  PYTORCH_VERSION_SUFFIX: "+cu111"
  TORCHVISION_VERSION: "0.9.0"
  TORCHVISION_VERSION_SUFFIX: "+cu111"
  TORCHAUDIO_VERSION: "0.8.0"
  TORCHAUDIO_VERSION_SUFFIX: ""
  PYTORCH_DOWNLOAD_URL: "https://download.pytorch.org/whl/torch_stable.html"

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ubuntu-cuda/**'
      - '.github/workflows/docker_build_1.8.0_py3.9.10_cuda11.1_ubuntu20.04.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker/ubuntu-cuda/build.sh

      - name: Push docker image
        run: docker push cnstark/pytorch:${PYTORCH_VERSION}-py${PYTHON_VERSION}-cuda${CUDA_VERSION}-ubuntu${UBUNTU_VERSION}
